data <- read.csv("../04_results/02_training_set_CLEAN.csv")
cat("Data structure:\n")
str(data)
cat("\n\nUnique civilian categories:\n")
cat(paste(unique(data$civilian_category), collapse = ", "))
cat("\n\nUnique skill levels:\n")
cat(paste(unique(data$skill_level), collapse = ", "))
cat("\n\nUnique ranks:\n")
cat(paste(unique(data$rank), collapse = ", "))
