#!/usr/bin/env Rscript
# Military Pay Dates & Inflation Analysis

library(tidyverse)

cat("\n╔════════════════════════════════════════════════════════════════╗\n")
cat("║         MILITARY PAY DATA - RECENCY & INFLATION REVIEW          ║\n")
cat("╚════════════════════════════════════════════════════════════════╝\n\n")

cat("MILITARY PAY SCALE SOURCE:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("Source: DFAS (Defense Finance & Accounting Service)\n")
cat("URL: https://www.dfas.mil/MilitaryMembers/payentitlements/Pay-Tables/\n")
cat("Date: January 2025 (CURRENT)\n")
cat("Status: ✓ MOST RECENT - Effective Jan 1, 2025\n\n")

cat("MILITARY PAY INCREASE HISTORY (Recent):\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("2024: 3.2% pay raise\n")
cat("2023: 8.7% pay raise (inflation response)\n")
cat("2022: 2.7% pay raise\n")
cat("2021: 3.0% pay raise\n\n")

cat("CIVILIAN SALARY DATA SOURCE:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("Source: BLS (Bureau of Labor Statistics) Public API\n")
cat("Series: CES0500000003 (Avg Hourly Earnings - All Private)\n")
cat("       CES0500000008 (Avg Hourly Earnings - Production Workers)\n")
cat("Date Range: January 2020 - December 2024 (HISTORICAL)\n")
cat("Status: ✓ MONTHLY DATA across 5 years\n\n")

cat("INFLATION CONTEXT:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("2020: ~1.4% inflation (pandemic start)\n")
cat("2021: ~4.7% inflation\n")
cat("2022: ~8.0% inflation (peak)\n")
cat("2023: ~4.1% inflation\n")
cat("2024: ~2.4% inflation (so far)\n")
cat("Cumulative 2020-2024: ~21% total inflation\n\n")

cat("ISSUE IDENTIFIED:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("⚠️  MILITARY PAY: January 2025 (current, not inflation-adjusted)\n")
cat("⚠️  CIVILIAN PAY: 2020-2024 (historical, includes past inflation)\n")
cat("⚠️  MISMATCH: We're comparing 2025 military pay to 2020-2024 civilian data\n\n")

cat("DO WE NEED INFLATION ADJUSTMENT?\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("SHORT ANSWER: Yes, but not critical for MVP. Here's why:\n\n")

cat("Option A: INFLATE CIVILIAN DATA TO 2025 (Recommended for accuracy)\n")
cat("  Pros:\n")
cat("    ✓ Compare apples-to-apples (both 2025 dollars)\n")
cat("    ✓ More accurate predictions for 2025 transitions\n")
cat("    ✓ Historical BLS data shows real trends\n")
cat("  Cons:\n")
cat("    ⚠️ Adds complexity\n")
cat("    ⚠️ CPI index needed\n")
cat("  Effort: 30 min (extract CPI data, apply adjustment)\n\n")

cat("Option B: DEFLATE MILITARY PAY TO HISTORICAL AVERAGE (Simpler)\n")
cat("  Pros:\n")
cat("    ✓ Keep all data in 2020-2024 range\n")
cat("    ✓ Simpler to implement\n")
cat("  Cons:\n")
cat("    ⚠️ Predictions are for 2020-2024, not current market\n")
cat("  Effort: 15 min (calculate average adjustment factor)\n\n")

cat("Option C: ACCEPT INFLATION MISMATCH (MVP shortcut)\n")
cat("  Pros:\n")
cat("    ✓ Fastest - use data as-is\n")
cat("    ✓ Model still learns relationships\n")
cat("  Cons:\n")
cat("    ⚠️ ~21% bias in predictions (too high)\n")
cat("    ⚠️ Not defensible for actual career decisions\n\n")

cat("RECOMMENDATION:\n")
cat("╔════════════════════════════════════════════════════════════════╗\n")
cat("║  Use OPTION A: Inflate Civilian Data to 2025                 ║\n")
cat("║  Rationale: 30 min of work for 21% accuracy improvement       ║\n")
cat("║  Outcome: All data in current 2025 dollars                    ║\n")
cat("║  Result: Model predicts realistic 2025 salaries               ║\n")
cat("╚════════════════════════════════════════════════════════════════╝\n\n")

cat("INFLATION ADJUSTMENT APPROACH:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("1. Extract CPI-U (Consumer Price Index) from BLS API\n")
cat("   Series: CUUR0000SA0 (already in our data!)\n\n")

cat("2. Calculate adjustment factor for each month:\n")
cat("   CPI_2025 / CPI_historical_month = adjustment factor\n\n")

cat("3. Multiply civilian salaries by adjustment factor:\n")
cat("   Salary_2025 = Salary_2020_2024 × (CPI_Dec2024 / CPI_month)\n\n")

cat("4. Result: All salaries normalized to December 2024 dollars\n\n")

cat("DATA WE ALREADY HAVE:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("✓ CPI data already extracted in bls_employment_earnings_compensation.csv\n")
cat("✓ Series: CUUR0000SA0 (CPI-U All Urban Consumers)\n")
cat("✓ Data: 2020-2024 monthly (60 data points)\n\n")

cat("NEXT STEPS:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("1. Load CPI data from BLS file\n")
cat("2. Calculate inflation factors by month\n")
cat("3. Apply to civilian hourly earnings\n")
cat("4. Annualize to salary (hourly × 2080 hours/year)\n")
cat("5. Merge with military profiles\n")
cat("6. Create training dataset\n\n")

cat("TIME ESTIMATE: 30 minutes for full inflation adjustment\n")
cat("MVP IMPACT: High (21% accuracy improvement)\n\n")
